version: '3.8'
services:
  service_db:
    container_name: service_db
    restart: unless-stopped
    networks:
      - service_network
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql
    build:
      context: database
      dockerfile: Dockerfile
      network: host
    deploy:
      replicas: 1
  service_ui:
    container_name: service_ui
    restart: unless-stopped
    networks:
      - service_network
    ports:
      - "80:3000"
    depends_on:
      - service_api
    build:
      context: web_app
      dockerfile: Dockerfile
    deploy:
      replicas: 1
  service_api:
    container_name: service_api
    restart: unless-stopped
    networks:
      - service_network
    ports:
      - "20001:20001"
    depends_on:
      - service_db
    build:
      context: ./api
      dockerfile: Dockerfile
    deploy:
      replicas: 1

networks:
  service_network:
    driver: bridge
volumes:
  db_data:
    name: service-db-data
